default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cmcostdb_dev

test:
  <<: *default
  database: cmcostdb_test

production:
  <<: *default
  database: cmcostdb_prod
